name: Auto update

on:
  schedule:
    - cron: '0 0 * * *'  # every day at midnight
  workflow_dispatch:

defaults:
  run:
    working-directory: ryujinx

jobs:
  update:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: 'master'
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          path: ryujinx
      - run: cinst au -y
      - run: ./update.ps1
      - uses: andstor/file-existence-action@v1
        id: check_files
        with:
          files: '**/*.nupkg'
      - run: choco push -k ${{ secrets.CHOCO_API_KEY }}
        if: steps.check_files.outputs.files_exists == 'true'
      - uses: peter-evans/create-pull-request@v4
        with:
          path: ryujinx
          delete-branch: true
          add-paths: |
            *.nuspec
            *.ps1
